# Generated by Django 6.0.2 on 2026-02-15 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat_type', models.CharField(choices=[('president', 'President'), ('governor', 'Governor'), ('senator', 'Senator'), ('mp', 'MP'), ('woman_rep', 'Woman Rep'), ('mca', 'MCA')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('National', 'National'), ('County', 'County'), ('Constituency', 'Constituency'), ('Ward', 'Ward')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('constituency', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('seat_type', 'county', 'constituency', 'ward'), name='unique_seat')],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('manifesto', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='voting_api.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voter_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['voter_code'], name='idx_voter_code'), models.Index(fields=['id_number'], name='idx_id_number')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_api.candidate')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_api.seat')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting_api.voter')),
            ],
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['seat'], name='idx_seat_id'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter'], name='idx_user_votes'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['seat'], name='idx_seat_votes'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['candidate'], name='idx_candidate_votes'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'seat'), name='one_vote_per_seat'),
        ),
    ]
