# Generated by Django 6.0.2 on 2026-03-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='constituency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='county',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='ward',
            field=models.IntegerField(),
        ),
    ]
