# Generated by Django 6.0.2 on 2026-04-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_api', '0002_alter_voter_constituency_alter_voter_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='constituency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='county',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='ward',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
