from django.urls import path
from .views import *
from .reports import *

urlpatterns = [
    path("timo", index),
    path("register", signup),
    path("login", login),
    path("vote", cast_vote),
    path("candidates", get_candidates),
    path("results", get_results),
    path("voter/status", voter_status),
    path("voter/change-password", change_password),
    path("voter/forgot-password", forgot_password),
    path("candidate/summarize", summarize_candidate),
    path("system-admin/login", admin_login),
    path("system-admin/stats", admin_stats),
    path("system-admin/voters", admin_voters),
    path("system-admin/candidates", admin_candidates),
    path("system-admin/votes", admin_votes),
    path("system-admin/toggle-halt", admin_toggle_halt),
    path("system-admin/candidates/add", admin_candidate_add),
    path("system-admin/candidates/force-load", force_load_candidates),
    path("system-admin/candidates/force-load/status", force_load_candidates_status),
    path("system-admin/candidates/<int:id>/delete", admin_candidate_delete),
    path("system-admin/candidates/delete-all", admin_candidate_delete_all),
    path("system-admin/voters/<int:id>/delete", admin_voter_delete),
    path("system-admin/voters/<int:id>/reset-password", admin_voter_reset_password),
    path("system-admin/voters/delete-all", admin_voter_delete_all),
    path("system-admin/restart-voting", admin_restart_election),
    path("results/leaders", get_all_leaders),
    path("results/analysis/ward/<int:ward_id>", get_ward_analysis),
    path("results/analysis/constituency/<int:constituency_id>", get_constituency_analysis),
    path("results/all_candidates", get_all_candidates_analysis),
    path("chat", chat_response),
    path("system-admin/reports/election-results", admin_report_election_results),
    path("system-admin/reports/voter-turnout", admin_report_voter_turnout),
    path("system-admin/reports/registered-voters", admin_report_registered_voters),
    path("system-admin/reports/audit-trail", admin_report_audit_trail),
    path("system-admin/reports/candidate-performance", admin_report_candidate_performance),
    path("system-admin/reports/regional-analysis", admin_report_regional_analysis),
    path("wards/", get_wards),
]